config/routes.rb
SqliteDevise2::Application.routes.draw do

  # Assigning User model to Devise
  devise_for :users

  # Defining root_url to app/views/pages/index.html.erb
  root :to => "pages#home"

  # Defining static pages
  match "home" => "pages#home"
  match "contact" => "pages#contact"
  match "about" => "pages#about"
  match "help" => "pages#help"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def help
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li,msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)
    html = <<-HTML
    <div class="notice" id="error_explanation">
      <p>#{sentence}</p>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
    
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to "logo", root_path %>
	<nav class="round">
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Help", help_path %></li>
			<% if user_signed_in? %> 
				<li>Signed in as <%= current_user.email %>. Not you? 
				<%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
			<% else %>
				<li><%= link_to "Sign up!", new_user_registration_path %> <%= link_to "Log in", new_user_session_path %></li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>

<%= stylesheet_link_tag 'blueprint/ie' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>SqliteDevise2</title>
		<%= javascript_include_tag 'application' %>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= render 'layouts/stylesheets' %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div id="container" class="container">
			<%= render 'layouts/header' %>

			<% flash.each do |name, msg| %>
			<% if msg.class == Array %>
			<% msg.each do |message| %>
			<%= content_tag :div, message, :id => "flash_#{name}" %>
			<% end %>
			<% else %>
			<%= content_tag :div, msg, :id => "flash_#{name}" %>
			<% end %>
			<% end %>
			<%= yield %>

			<%= render 'layouts/footer' %>
			<% logger.info("\n### Controller: "+params[:controller]+"\n### Action: "+params[:action]+"\n") if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Home</h1>
<p>Find me in app/views/pages/home.html.erb</p>